sonar.projectKey=joblify_talent-flow
sonar.projectName=Joblify Talent Flow Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts

sonar.exclusions=dist/**,node_modules/**,playwright-report/**,test-results/**,.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
